name: Scheduled post

on:
  push:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dxh30/publish-schedule-action@v1.1
      with:
        time_range_minutes: 720
        content_directory: content
      id: publish
    - name: Run something else
      if: steps.publish.output.is.scheduled == 'true'
      run: echo "It is scheduled!"
